### ISSUE TITLE
Crash on collapse 

### ISSUE THREAD

**Issue by MrBreakNFix** [FlorianMichael/fabric-imgui-example-mod#4]
Using the unmodified code from the repository, without making any changes, if you launch the game and go to the title screen, you see the following windows:
![image](https://github.com/FlorianMichael/fabric-imgui-example-mod/assets/73456238/9c1e1600-01a2-4f38-8099-8f35ac316f42)

When clicking on this button on the demo window, it collapses, as intended.
![image](https://github.com/FlorianMichael/fabric-imgui-example-mod/assets/73456238/6ad4cf21-a7d2-4a81-a40e-d90a27ae37c8)

But if the same is done on the Hello World window:
![image](https://github.com/FlorianMichael/fabric-imgui-example-mod/assets/73456238/1d275898-4158-489b-a948-5af057cd74a5)

The game instantly crashes.

![image](https://github.com/FlorianMichael/fabric-imgui-example-mod/assets/73456238/b6467e32-c6c3-429b-a8e5-0898045deb87)

![image](https://github.com/FlorianMichael/fabric-imgui-example-mod/assets/73456238/52b8c492-62a5-4854-a5ff-2e958d5d4a3c)

Thank you, I will make a PR if I figure it out.

**Comment by florianreuth** [comment]
Thanks for reaching me out, the reference to ImGui#render is irrelevant here because all draw calls/operations are passed through this method. The issue was that ImGui#end() for this window was wrapped inside begin() causing it to not be called anymore when you close the window, this can be fixed by just moving begin() outside the if block

**Comment by MrBreakNFix** [comment]
Ah, thanks so much for clearing this up!

**Comment by florianreuth** [comment]
No problem
